pipeline {
    agent any
    environment {
        AWS_REGION = 'us-east-1'
        ECR_BACKEND = '569681419462.dkr.ecr.us-east-1.amazonaws.com/backend-repo'
        ECR_FRONTEND = '569681419462.dkr.ecr.us-east-1.amazonaws.com/frontend-repo'
    }
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/YOUR_GITHUB_REPO.git'
            }
        }

        stage('Build Backend Image') {
            steps {
                sh 'docker build -t $ECR_BACKEND ./backend'
                sh 'docker push $ECR_BACKEND'
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh 'docker build -t $ECR_FRONTEND ./frontend'
                sh 'docker push $ECR_FRONTEND'
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}
